# site settings
title: Skyler Friedline
subtitle: Loves Bacteria
email: skyler@skybio.space
description: I'm a science enthusiast with a drive to solve global problems with human-microbe cooperation.

baseurl: "" # the subpath of your site, e.g. /blog
url: # the base hostname & protocol for your site
author:


# homepage tiles
tiles-source: pages # accepts "posts" or "pages"
tiles-count: 6

# social settings (key must match name of font awesome icon)
# see https://fontawesome.com/icons?d=gallery&p=2&s=brands
# Icons are not shown if value is empty
# You need to restart jekyll for changes to have an effect
socials:
  GitHub: https://github.com/skylerbio
  LinkedIn: https://www.linkedin.com/in/sefriedline
  icon alt fa-envelope: mailto:skyler@skybio.space
  fa-sharp fa-solid fa-graduation-cap: https://scholar.google.com/citations?user=Ya9SG8MAAAAJ&hl=en&oi=ao

# build settings
markdown: kramdown

sass:
  style: compressed

exclude:
- "*.gemspec"
- LICENSE.md
- CONTRIBUTING.md
- README.md 
